/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 */
package cybersecurityserver;

import cybersecurityserver.alpha.DBOperations;
import cybersecurityserver.alpha.UsermasterBean;
import cybersecurityserver.util.FTPServer;
import java.awt.Container;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.JOptionPane;

/**
 *
 * @author vinay
 */
public class MainFrame extends javax.swing.JFrame implements WindowListener {

    UsermasterBean objUsermasterBean;
    static Container container;
    static int userId;
    public static String username;
    int userActivityID;

    /** Creates new form MainFrame */
    public MainFrame() {
        //initComponents();
        //setVisible(true);
    }

    public MainFrame(UsermasterBean objUsermasterBean, int userActivityID) {
        initComponents();
        this.objUsermasterBean = objUsermasterBean;
        userId = objUsermasterBean.getUserId();
        username = objUsermasterBean.getUsername();
        this.userActivityID = userActivityID;

        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        setResizable(false);


        container = getContentPane();
        if (objUsermasterBean.getUserType().equalsIgnoreCase("employee")) {
            mbMainFrame.remove(mnuUserMaintenance);
            mbMainFrame.remove(mnuReports);
            mbMainFrame.remove(mnuServer);
        }

        addWindowListener(this);
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mbMainFrame = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        miLogout = new javax.swing.JMenuItem();
        mnuProfile = new javax.swing.JMenu();
        miProfileDetail = new javax.swing.JMenuItem();
        mnuUserMaintenance = new javax.swing.JMenu();
        miUserDetail = new javax.swing.JMenuItem();
        mnuServer = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuReports = new javax.swing.JMenu();
        miUserReport = new javax.swing.JMenuItem();
        miUserActivityreport = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CyberSecurityServer");

        mnuFile.setText("File");

        miLogout.setText("Logout");
        miLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLogoutActionPerformed(evt);
            }
        });
        mnuFile.add(miLogout);

        mbMainFrame.add(mnuFile);

        mnuProfile.setText("Profile");

        miProfileDetail.setText("Profile Detail");
        miProfileDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProfileDetailActionPerformed(evt);
            }
        });
        mnuProfile.add(miProfileDetail);

        mbMainFrame.add(mnuProfile);

        mnuUserMaintenance.setText("User Maintenance");

        miUserDetail.setText("User Detail");
        miUserDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUserDetailActionPerformed(evt);
            }
        });
        mnuUserMaintenance.add(miUserDetail);

        mbMainFrame.add(mnuUserMaintenance);

        mnuServer.setText("Server");

        jMenuItem1.setText("Start Server");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuServer.add(jMenuItem1);

        mbMainFrame.add(mnuServer);

        mnuReports.setText("Reports");

        miUserReport.setText("User Report");
        miUserReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUserReportActionPerformed(evt);
            }
        });
        mnuReports.add(miUserReport);

        miUserActivityreport.setText("User Activity Report");
        miUserActivityreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUserActivityreportActionPerformed(evt);
            }
        });
        mnuReports.add(miUserActivityreport);

        mbMainFrame.add(mnuReports);

        setJMenuBar(mbMainFrame);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miUserDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUserDetailActionPerformed
        // TODO add your handling code here:
        container.removeAll();
        UserDetail objUserDetail = new UserDetail();
        objUserDetail.setBounds(250, 100, 460, 500);
        container.setVisible(false);
        container.add(objUserDetail);
        container.setVisible(true);
}//GEN-LAST:event_miUserDetailActionPerformed

    private void miLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLogoutActionPerformed
        // TODO add your handling code here:
        logout();
}//GEN-LAST:event_miLogoutActionPerformed

    private void miProfileDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProfileDetailActionPerformed
        // TODO add your handling code here:
        container.removeAll();
        ProfileDetail objUserDetail = new ProfileDetail();
        objUserDetail.setBounds(250, 100, 438, 400);
        container.setVisible(false);
        container.add(objUserDetail);
        container.setVisible(true);
    }//GEN-LAST:event_miProfileDetailActionPerformed

private void miUserReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUserReportActionPerformed
    // TODO add your handling code here:
    new UserReport();
}//GEN-LAST:event_miUserReportActionPerformed

private void miUserActivityreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUserActivityreportActionPerformed
    new UserActivityReport();
}//GEN-LAST:event_miUserActivityreportActionPerformed

private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
// TODO add your handling code here:

    FTPServer objServer = new FTPServer();
    objServer.start();
    JOptionPane.showMessageDialog(this, "Server Started Successfully");

}//GEN-LAST:event_jMenuItem1ActionPerformed

    void logout() {
        DBOperations objDB = new DBOperations();
        objDB.updateUserActivity(userActivityID);
        System.exit(0);
    }

    @Override
    public void windowOpened(WindowEvent e) {
    }

    @Override
    public void windowClosing(WindowEvent e) {
        logout();
    }

    @Override
    public void windowClosed(WindowEvent e) {
    }

    @Override
    public void windowIconified(WindowEvent e) {
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
    }

    @Override
    public void windowActivated(WindowEvent e) {
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar mbMainFrame;
    private javax.swing.JMenuItem miLogout;
    private javax.swing.JMenuItem miProfileDetail;
    private javax.swing.JMenuItem miUserActivityreport;
    private javax.swing.JMenuItem miUserDetail;
    private javax.swing.JMenuItem miUserReport;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuProfile;
    private javax.swing.JMenu mnuReports;
    private javax.swing.JMenu mnuServer;
    private javax.swing.JMenu mnuUserMaintenance;
    // End of variables declaration//GEN-END:variables
}
